### ISSUE TITLE
Syntax error in src/PhoneNumber.php

### ISSUE THREAD

**Issue by tomzi** [brick/phonenumber#4]
**Hello**,

Just wanted to warn you there is a syntax error on line 106 in the file.
A "?" symbol is making all crash.

Btw thanks for the plugin !
Cheers,
Thomas

**Comment by BenMorel** [comment]
Hi, you're getting a syntax error because you're likely using PHP 7.0.
This question mark is a [nullable type introduced in PHP 7.1](http://php.net/manual/fr/migration71.new-features.php), which is the minimum PHP version supported in version `0.2.*`.

You can still use version `0.1.*` to get support for PHP 5.6 and PHP 7.0!
